default: &default
  adapter: postgresql
  encoding: utf8
  username: adacer
  password: adacer2012
  database: myapp
  host:     localhost
  pool: 5


test:
  <<: *default

development:
  <<: *default
  database: myapp
production:
  <<: *default
